stages:
  - build
  - scan
  - deploy

variables:
  API_IMAGE_NAME: pursuitpal_api:latest

# Build API Docker image locally on the server
build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker build -t $API_IMAGE_NAME .
  tags:
    - e2e_prod_server

# Run vulnerability scan on API code
scan:
  stage: scan
  image: registry.gitlab.com/gitlab-org/security-products/analyzers/gemnasium:2
  script:
    - /analyzer run
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
  tags:
    - e2e_prod_server
  allow_failure: true

# Deploy API to production
deploy:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker stop pursuitpal_api || true
    - docker rm pursuitpal_api || true
    - docker run -d --name pursuitpal_api -p 5000:5000 $API_IMAGE_NAME
  tags:
    - e2e_prod_server
  environment:
    name: production
  only:
    - master, release*
